spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/fly
    username: postgres
    password: 1234
    hikari:
      maximumPoolSize: 50
      minimumIdle: 10
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      table-name: SPRING_SESSION

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#  batch:
#      job:
#        enabled: false
#      jdbc:
#          initialize-schema: always
#
logging:
  level:
    root: INFO
    org:
      apache:
        tomcat: ${logging.level.root}
        catalina: ${logging.level.root}
      hibernate:
        SQL: ${logging.level.root}
        type:
          descriptor:
            sql:
              BasicBinder: ${logging.level.root}
